### ISSUE TITLE
all the txs are successfull

### ISSUE THREAD

**Issue by troggy** [leapdao/burner-wallet#1]
as our node currently always responds with success on `sendRawTransaction`, this never displays an error:
https://github.com/leapdao/burner-wallet/blob/master/src/App.js#L2038-L2046

**Comment by pinkiebell** [comment]
Todo: fix transaction receipt in leap-node. Keep a log of included transactions which get pruned after some time...

**Comment by TimDaub** [comment]
This was fixed in #57
