### ISSUE TITLE
Integrate bity FIAT off-ramp

### ISSUE THREAD

**Issue by TimDaub** [leapdao/burner-wallet#107]
## Scope

- [Here](https://github.com/austintgriffith/burner-wallet/issues/177) is the original idea for integrating bity
- Bity allows a user to off-ramp ETH <=> 5000 CHF annually. It only requires authentication through a mobile phone number
- Bity only works in the EU at this point. Make this sufficiently clear to the user.
- Use bity's API to off-ramp a user's eth as outlined in their documentation: https://doc.bity.com/backend/v2.html#place-an-order
- Consider storing some of the user's credentials (e.g. phone number) in the wallet's local storage for even faster off-ramping.
- Discuss whether or not it is safe to store the user's bank account of second off-ramping too. Personally, I think it's not secure though.
- Bonus: Reach out to bity and ask if they're interested in integrating with our main net for even faster off-ramping
- Make the user aware of the annual off-ramping limit of 5000 CHF by querying the past orders of the user and summing up their withdrawals to show it in the UI

## Deliverables

- A dialogue in the Exchange view of the burner wallet that lets the user off-ramp crypto into fiat very quickly

## Gain for the project

- Allows users to exchange their crypto for FIAT without much friction
- Proves to newly onboarded users that pDAI/ETH is in fact valuable

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by vrde** [comment]
> Use bity's API to off-ramp a user's eth as outlined in their documentation: https://doc.bity.com/backend/v2.html#place-an-order

Seems like they changed the URL, the new one is https://doc.bity.com/exchange/v2.html#place-an-order
