### ISSUE TITLE
Whitelabel burner-wallet to make it look like a LeapDAO product and further include rimble-ui

### ISSUE THREAD

**Issue by TimDaub** [leapdao/burner-wallet#108]
## Scope

- Change all colors and logos of the burner-wallet
- Change the manifest.json, twitter previews, etc.
- Change `<title>` and everything else in `public/index.html`
- Change all occurrences of the word xDAI to pDAI (or whatever we want to call it)
- Add pDAI burner wallet logo
- Consider using rim branch (Rimble-UI). It's rebased in the cinemarket branch
- Change "About" and "Code" links in Advanced menu
- Browser header should match LeapDAO colors:

![image](https://user-images.githubusercontent.com/2758453/58014104-5b139980-7af8-11e9-9b15-cc87622f2518.png)

- QR code on Receive.js and Request.js is too small. Replace all occurrences of "qrcode.react" with rimble-ui's QRcode: 
<img width="777" alt="Screen Shot 2019-05-20 at 17 24 31" src="https://user-images.githubusercontent.com/2758453/58033125-32a19480-7b24-11e9-9ebe-afbc485e4798.png">
- Make "Cancel" a secondary button. Align all items in box horizontally in Exchange.js dialogue
<img width="744" alt="Screen Shot 2019-05-20 at 17 50 01" src="https://user-images.githubusercontent.com/2758453/58034872-d0e32980-7b27-11e9-9c11-d437fb106d94.png">
- Align "Send ETH" and "Send DAI" button in Exchange.js with rest of view
- Advanced.js doesn't have the same margin left and right as the main view has. Additionally it looks like the text inputs do not align with the buttons
<img width="769" alt="Screen Shot 2019-05-20 at 18 10 13" src="https://user-images.githubusercontent.com/2758453/58036133-ad6dae00-7b2a-11e9-8f64-01e110e6791f.png">

## Dependencies

We recommend first resolving #110 and then this issue.

## Deliverables

- A burner-wallet that looks like a LeapDAO product

## Gain for the project

- Increased brand awareness and brand building

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by StevenJNPearce** [comment]
@TimDaub I will implement this weekend, unless you were planning on doing it yourself?

**Comment by TimDaub** [comment]
Hi @StevenJNPearce, thanks for your interest. @MaxStalker already commented on Slack that he's on the issue. Simply wasn't able to assign it to him as he's not part of the LeapDAO org.

While I'd love your help on the milestone, I think all issues are assigned already :/
But let's chat in Slack (username: Tim), maybe we can find something!

**Comment by johannbarbie** [comment]
delivered here: https://github.com/leapdao/burner-wallet/pull/157
