### ISSUE TITLE
Proposal to reduce the divergence of LeapDAO's burner-wallet fork with upstream

### ISSUE THREAD

**Issue by TimDaub** [leapdao/burner-wallet#109]
[_This item is not directly actionable. Instead it's more of a long-term guideline of what we'd like to achieve in terms of code quality. To see all currently actionable bounties go [here](https://github.com/leapdao/burner-wallet/milestone/2)_]

## Context

LeapDAO is planning to allocate a budget to making the burner-wallet part of their product offerings. The steps that lead up to this development are outlined in this sprint: https://github.com/leapdao/burner-wallet/milestone/2

LeapDAO has already forked and used the burner-wallet on two occasions:
- At Blocksplit, the burner-wallet was used by conference visitors to transact sunDAI on the LeapDAO mainnet.
  - Code: https://github.com/leapdao/burner-wallet/pull/30
  - Domain: sundai.io
- At Cannes Film Festival, the burner-wallet is being used to register movie NSTs on LeapDAO's staging-testnet and to buy beers from those profits
  - Code: https://github.com/leapdao/burner-wallet/tree/cinemarket

The code produced on these two occasions already diverges significantly from Austin's code upstream. In the sprint mentioned above, LeapDAO would like to make the burner-wallet a PayPal replacement for Europe by providing frictionless crypto/FIAT on- and off-ramps, changing its design, etc.. If done incorrectly however, this will increase the divergence with upstream even more.

## Problems in unifying upstream and LeapDAO's burner-wallet fork

- Metamask is currently not natively supporting LeapDAO's RPC interface. Instead transaction signing has to be called manually
- leap-core's transaction creation process diverges from mainnet web3 transaction creation
- To make the burner-wallet more maintainable, LeapDAO would like to make some drastic changes to the burner-wallet's architecture. It is unclear how welcome these changes are upstream.

## The current burner-wallet architecture

The burner-wallet's architecture can be visualized like this:

<img width="658" alt="Screen Shot 2019-05-13 at 14 12 38" src="https://user-images.githubusercontent.com/2758453/57620492-32842080-7589-11e9-9b6e-ded331e7972d.png">

Highlights:

- The state of the app is stored in the react components
- App.js is storing a majority of the state of all other components
- Routing is done manually through a `switch` statement
- App.js and other components connect with Dapparatus to load some data initially. Dapparatus is not consistently leveraged throughout the app
- Web3.js is required in both Dapparatus and the burner-wallet with multiple instances initiated
- While the `metaAccount` is created in Dapparatus, it's propagated to App.js immediately and stored in its state

## Improving on the architecture

LeapDAO would like to change the burner-wallet's architecture as follows:

<img width="677" alt="Screen Shot 2019-05-13 at 15 32 23" src="https://user-images.githubusercontent.com/2758453/57625550-5dc03d00-7594-11e9-9d6b-f2c56ad8782b.png">

Highlights mainly consist of separating the burner-wallet in two distinct modules:

1. burner-core: Takes over 99% of all account and network related functionality like:
   - Creating and storing private and public key
   - Proxying all network calls to plugins (web3.js and leap-core currently)
   - Implements utility functions for the `metaAccount` like fetching the latest gas price of the network
2. burner-wallet: Mainly UI component logic
   - Implements a mobx store for handling state (e.g. transaction history synced with `localStorage`)
   - Stops relying on Dapparatus
   - Connects to the chain via the burner-core

#### Benefits of the proposed architecture

- More DRY codebase and separation of concern
- If welcomed upstream: Reduced divergence of code bases
- Plasma, POA and Mainnet compatibility in the burner wallet without mixing code bases
- burner-core can easily be unit-tested and allows for a safer and more robust burner-wallet

## Execution and Budget

LeapDAO is allocating a budget from its ecosystem-development fund to allow the burner-wallet to transact with pDAI/DAI/ETH. The tasks covered under this budget are outlined in this [milestone](https://github.com/leapdao/burner-wallet/milestone/2). A large refactor as outlined above might not be fully covered by the ecosystem-development fund at this point, hence we're proposing to execute the refactor as a "[StranglerFigApplication](https://martinfowler.com/bliki/StranglerFigApplication.html)". In a nutshell, we're isolating only the absolutely necessary parts into a separate module (e.g. the _burner-core_) until that module is eventually strong enough to take over a large majority of the burner-wallet's functionality (it _strangles_ its host). If successful, we repeat the process with other proposed changes (e.g. router integration, the mobx-store, etc.).

From a high-level view, we propose the following changes (sorted by priority):

- Separate all network and account logic into a separate module ("burner-core")
  - Allow burner-core to have plugins to bridge the gap between web3.js and leap-core
- Get rid of most logic in Dapparatus
- Replace all react state with a react store (e.g. mobx)
- Help improve on [_burner-modules_](https://medium.com/gitcoin/burner-modules-c6737cf06fe)

Other changes we'd love to see upstream but that are not a main concern at this point:

- Codebase formatted with prettier
- Tests
- [Rimble-UI branch](https://github.com/austintgriffith/burner-wallet/tree/rim) merged into master
- A config.json with all the burner-wallet's magic constants

**Comment by StevenJNPearce** [comment]
I don't think it's worth reducing divergence with upstream; it's a mess, ~100 unused variables, code everywhere there was written in a hurry for a hackathon. The new architecture would make this a joy to work on.

**Comment by TimDaub** [comment]
@dmihal was inspired by this issue and wrote a great spec for the burner-wallet: https://docs.google.com/document/d/1GtS_NxhxSt9XVTphp4fWRvjeQjIVT8WbYsqpKAlWbfE/edit
