### ISSUE TITLE
Rebase cinemarket branch and merge into master

### ISSUE THREAD

**Issue by TimDaub** [leapdao/burner-wallet#110]
## Scope

- The #cinemarket branch is the one that's furthest ahead currently. It includes the #sundai branch.
- #cinemarket uses Rimble-UI. That's a major divergence from upstream (Austin has a branch called rim) but it makes whitelabeling much easier as it has a `theme.js` file.
- Remove all cinemarket-specific logic (e.g. RegisterMovie.js, Uploader.js) and change existing components that have been adjusted (e.g. SendBadge.js)
- Add deleted components back in. E.g. revert this PR: https://github.com/leapdao/burner-wallet/pull/75

## Deliverables

- A rebased version of #cinemarket 
- Manually test basic functionality on different browsers to make sure everything still works

## Gains for the project

- We utilize last months work (e.g. bug fixes, etc.) on the burner wallet
- It's easy to style with Rimble-UI

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 70%
bounty reviewer: name / 20%

**Comment by johannbarbie** [comment]
are there any changes that we have done on the sunDAI branch that would also be worth merging?

**Comment by TimDaub** [comment]
I merged sunDai in cinemarket. So it's included if we merge cinemarket.
