### ISSUE TITLE
Reduce burner-wallet footprint

### ISSUE THREAD

**Issue by TimDaub** [leapdao/burner-wallet#116]
## Scope

- The burner-wallet's packaged source code is currently 12-14MB
- It has a really poor Google PageSpeed ranking: https://github.com/austintgriffith/burner-wallet/issues/57
- There are some low hanging fruits to fix this: http://lmgtfy.com/?q=Improve+google+pagespeed, like properly minimizing all assets
- Loading times could also improved by caching, enabling gzip etc. In this issue we'd like to explore everything that makes loading faster
- Many dependencies might not be used in the code base or falsely declared as `depencencies`, when really they're `devDependencies`
- There should also be analysis tools that help to check the npm dependency tree for large packages: https://bundlephobia.com/scan-results?packages=@uppy/aws-s3@0.30.4,@uppy/core@0.30.4,@uppy/react@0.30.4,autolinker@2.2.1,axios@0.18.0,base64url@3.0.1,bootstrap@4.1.3,buffer@5.2.1,cors@2.8.4,crypto@1.0.1,eccrypto@1.1.0,eth-crypto@1.3.2,eth-ens-namehash@2.0.8,ethereum-mnemonic-privatekey-utils@1.0.5,ethereumjs-tx@1.3.7,ethereumjs-util@6.0.0,jimp@0.6.0,jsbi-utils@1.0.0,jsonp@0.2.1,leap-core@0.30.1,qrcode-reader@1.0.4,qrcode.react@0.8.0,query-string@6.3.0,react@16.6.0,react-blockies@1.4.0,react-cookies@0.1.0,react-dom@16.6.0,react-emoji-render@0.5.0,react-file-reader-input@2.0.0,react-input-range@1.3.0,react-linkify@0.2.2,react-qr-reader@2.1.1,react-scroll@1.7.10,react-stack-grid@0.7.1,rimble-ui@0.4.2,s3@4.4.0,scrypt@6.0.3,styled-components@4.1.3,tabookey-gasless@0.3.3,uuid@3.3.2,web3@1.0.0-beta.36

## Deliverables

- X% less kB footprint
- ideally Y seconds quicker load times (measure before and after)

## Gain for the Project

- Better user experience when using the burner wallet => quicker adoption?

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by sunify** [comment]
https://github.com/ai/size-limit
https://chrisbateman.github.io/webpack-visualizer/ (probably need to eject CRA scripts)
