### ISSUE TITLE
Network detection for DAI to ETH exchange is broken

### ISSUE THREAD

**Issue by troggy** [leapdao/burner-wallet#146]
It always complains about Mainnet, even when it is on mainnet. Thus DAI → ETH exchange is effectively not available

![2019-05-28 16-40-39 2019-05-28 16_41_44](https://user-images.githubusercontent.com/163447/58482795-bc2a1580-8167-11e9-9ba7-cad23473258a.gif)

**Comment by TimDaub** [comment]
## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%
