### ISSUE TITLE
in firefox 66.0.4 (64-bit) rootchain balance not displayed.

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#154]
balance of [5 MNY](https://rinkeby.etherscan.io/token/0xd2d0f8a6adff16c2098101087f9548465ec96c98?a=0x71810a9c58bed0def2102c6455badae4e6145b18) and [0.1 ETH](https://rinkeby.etherscan.io/address/0x71810a9c58bed0def2102c6455badae4e6145b18) not displayed:
<img width="851" alt="Screen Shot 2019-06-06 at 1 49 00 PM" src="https://user-images.githubusercontent.com/659301/59030662-df3c7f80-8861-11e9-92bc-34f4c6354ed1.png">

CORS errors in console.

same thing working well in chrome

**Comment by TimDaub** [comment]
This must have been a temporary issue with Infura that is now resolved. Closing.
