### ISSUE TITLE
transaction history not displayed on recipient

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#27]
# sender:

<img width="616" alt="Screen Shot 2019-04-12 at 3 55 41 PM" src="https://user-images.githubusercontent.com/659301/56042511-83f78080-5d3b-11e9-9e80-2933d48af14c.png">

# recipient
## these screens should display the history:
![Screenshot_20190412-155629](https://user-images.githubusercontent.com/659301/56042702-f7998d80-5d3b-11e9-9ac2-63e669187e36.jpg)

![Screenshot_20190412-155715](https://user-images.githubusercontent.com/659301/56042635-d33db100-5d3b-11e9-8c6b-20c9ca4832ed.jpg)

**Comment by TimDaub** [comment]
This only happens on clients that display network "Unknown".

**Comment by TimDaub** [comment]
Fixed in #37
