### ISSUE TITLE
Withdraw from another address not working (+other issues)

### ISSUE THREAD

**Issue by eshavkun** [leapdao/burner-wallet#29]
Precoditions:
* User already has burner wallet with some pDAI/sunDAI
* QR-code with private key for another wallet with some funds

Reproduction:
1. Scan QR-code from prerequisites
1. Withdraw screen opens - OK
1. Try to withdraw funds to your wallet
1. No mater what amount user wants to withdraw error is shown - WRONG - user should be able to withdraw funds

See attached screenshot with highlighted issues:
1. `xdai` instead of `pDai` or `sunDAI`
1. It shows "target" (user's) balance but that's not clear
1. Doesn't show balance of "source" account (the one from QR code)
1. Error message is shown no mater the amount user enters

![Screenshot_20190413-160428_mod](https://user-images.githubusercontent.com/28968492/56081267-a8bb2900-5e0b-11e9-9ef0-b27ce4e61241.png)

**Comment by TimDaub** [comment]
Fixed in #44 and merged into #30. Will close.
