### ISSUE TITLE
Deploy burner.leapdao.org automatically using travis-ci via github-pages

### ISSUE THREAD

**Issue by TimDaub** [leapdao/burner-wallet#36]
## Scope

- Write a .travis.yml file that automatically deploys the burner-wallet to either:
  - a Github pages repo
  - an S3 bucket + invalidates cloudfront cache
- An example of this can be found here: https://github.com/0xdefaceme/demo/blob/master/.travis.yml#L12
- If hosting on Github Pages, configure the domain like following:
<img width="1023" alt="Screen Shot 2019-05-13 at 10 07 10" src="https://user-images.githubusercontent.com/2758453/57605421-e45e2580-7566-11e9-805e-aec2e5acbc7b.png">
<img width="1023" alt="Screen Shot 2019-05-13 at 10 07 23" src="https://user-images.githubusercontent.com/2758453/57605436-eb853380-7566-11e9-9f7e-2f37974bb727.png">

## Deliverables

- burner-wallet deployed automatically on every master branch commit to a given domain
- Run eslint on travis and block merging PR if doesn't pass

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
This could be interesting too: https://medium.com/@felice.geracitano/brotli-compression-delivered-from-aws-7be5b467c2e1 via @sunify

**Comment by johannbarbie** [comment]
> brotli

interesting, i've done a similar setup for fonts with lambda before.

**Comment by troggy** [comment]
@TimDaub how do you run eslint now?
