### ISSUE TITLE
support fast exits

### ISSUE THREAD

**Issue by troggy** [leapdao/burner-wallet#4]
## Scope
- add fast exit market maker to burner wallet
- do not expect client to be online (keep receipt on backend)
- integrate exit with [sunDAI <-> DAI market](https://github.com/leapdao/burner-wallet/issues/5)

### Publicly visible delivery
- documentation in repo

## Deliverables
- working button on burner wallet

## Roles: 
bounty gardener: name / share 
bounty worker: name / share 
bounty reviewer: name / share

**Comment by troggy** [comment]
related change https://github.com/leapdao/exit-market-maker/issues/5

**Comment by troggy** [comment]
TODO:
- [x] add fast exit market maker to burner wallet
- [x] do not expect client to be online (keep receipt on backend)
- [ ] integrate exit with sunDAI <-> DAI market
- [ ] documentation in repo
- [x] working button on burner wallet
- [ ] setup mainnet exit-market-maker
- [ ] test with sundai.io
- [ ] test with mainnet

**Comment by TimDaub** [comment]
@troggy Can we close this?

**Comment by troggy** [comment]
I guess so
