### ISSUE TITLE
finish styling for SunDAI

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#40]
## Required
- make sure icon and name are used everywhere
- shouldn't say `Testnet` if on mainnet. better: `Leap Network`
- browser tab should have "SunDAI"
- links in advanced should point to leapdao

## Deliverables
- code running on sunDai.io

gardener: @johannbarbie | 10 %
worker: | 70%
reviewer: 20%

**Comment by troggy** [comment]
Resolved with 

https://github.com/leapdao/burner-wallet/commit/d75f0e4713fa0bde5cc7226f1067333c3d86b657
https://github.com/leapdao/burner-wallet/commit/15494b544b8bc8b73ff5ed07c29e1d6e14fb2e47
https://github.com/leapdao/burner-wallet/commit/11326360bc22d8f42cbb04e351076a5afe3f6e19
https://github.com/leapdao/burner-wallet/commit/4ea246ae7ed205ec5fb09a68e9844d3112604a15
#54
#55
