### ISSUE TITLE
out of gas when depositing into sunDai

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#46]
from metamask browser:
https://etherscan.io/tx/0xfb0d12a13062eab3c43481a73a98e6820770aa8ba628d5bfd53ed129b74ccb6a

more gas worked: 
https://etherscan.io/tx/0x6920260feeb6e55ee57461c71564ba04c215a10b6db875724d575596b92b598d

**Comment by troggy** [comment]
via #56
