### ISSUE TITLE
double approval when depositing from non-metamask account

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#47]
tried DAI -> SunDAI deposit on my mobile: approve was executed 2 times:
https://etherscan.io/tx/0xa66d98b3ec1f0fc578e98663f8f4fba47fcff7fed5ca40680f672fa4583b1451
https://etherscan.io/tx/0xb0e1135b3670496e606969e68d39064c480afd4c9555aad80f70ba3404cc7de9

**Comment by troggy** [comment]
This seems correct.

First tx approves sunDai contract to transfer DAI from you, so that `_pullAndMint` can work
Second tx approves ExitHandler to transfer DAI from you, so that it can pull DAI in `deposit` function

**Comment by troggy** [comment]
Two approvals should happen only for sunDAI setup, for LEAP only (e.g. burner.leapdao.org) it should still be just one approve
