### ISSUE TITLE
remove suggestion to exchange xDAi for ETH

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#48]
![Screenshot_20190424-093123__01](https://user-images.githubusercontent.com/659301/56640930-6c41c580-6674-11e9-9e74-be0059395037.jpg)

**Comment by troggy** [comment]
🤦‍♂️

**Comment by troggy** [comment]
@johannbarbie what to do to get this suggestion?

**Comment by troggy** [comment]
via #54
