### ISSUE TITLE
when trying to send ETH form the exchange view (arrow to the right), a plasma transfer is executed

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#49]
pressing this button in exchange under ETH:
<img width="197" alt="Screen Shot 2019-04-24 at 9 26 54 AM" src="https://user-images.githubusercontent.com/659301/56640999-9b583700-6674-11e9-84a9-ded208d18b03.png">

sunDAi is transfered:

<img width="1092" alt="Screen Shot 2019-04-24 at 9 18 26 AM" src="https://user-images.githubusercontent.com/659301/56640982-94312900-6674-11e9-85f6-32bfb6dfe293.png">

**Comment by troggy** [comment]
cannot reproduce.
1. ETH transfer is not working (and seems to never worked) with metamask
2. with meta accounts it works

Could it be that you have an unsigned request in metamask from some previous operation? @johannbarbie

**Comment by troggy** [comment]
via #58
