### ISSUE TITLE
when trying to send DAI from exchange view, an approval is started

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#50]
when pressing this button next to DAI:
<img width="197" alt="Screen Shot 2019-04-24 at 9 26 54 AM" src="https://user-images.githubusercontent.com/659301/56641079-cb9fd580-6674-11e9-95e4-ab8e1e9147f0.png">

approval is started:

<img width="1088" alt="Screen Shot 2019-04-24 at 9 21 23 AM" src="https://user-images.githubusercontent.com/659301/56641070-c478c780-6674-11e9-898b-1bd8b0393103.png">

**Comment by troggy** [comment]
solved with #51
