### ISSUE TITLE
DAI to ETH exchange fails for certain amounts

### ISSUE THREAD

**Issue by troggy** [leapdao/burner-wallet#53]
Given:
- meta account
- trying to convert 0.01 DAI to ETH

Result:
![image](https://user-images.githubusercontent.com/163447/56654333-842b4080-6698-11e9-8020-d66140f74e3b.png)

**Comment by TimDaub** [comment]
Looks like a number is not being cast to wei with `utils.toWei()`

**Comment by troggy** [comment]
addressed in upstream: https://github.com/austintgriffith/burner-wallet/pull/195

**Comment by TimDaub** [comment]
Will be addressed in https://github.com/leapdao/burner-wallet/issues/137
