### ISSUE TITLE
Remove l11n from the wallet

### ISSUE THREAD

**Issue by eshavkun** [leapdao/burner-wallet#62]
Currently wallet is automatically localized depending on locale setting. This should be switched off and the wallet should always be in English

**Comment by johannbarbie** [comment]
https://github.com/austintgriffith/burner-wallet/blob/master/src/i18n/index.js#L46

**Comment by TimDaub** [comment]
Removed languages for cinemarket in #101

**Comment by TimDaub** [comment]
I think for the PDAI burner-wallet we'd like i18n translation, don't we?
Hence, I'm closing this issue. Feel free to reopen if necessary.

**Comment by johannbarbie** [comment]
yeah, +1 on localization
